import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NNM STARTER</title>
        <meta name="description" content="Generated by EXPRESSD3V WEB ENGINEERS" />
      </Head>
      Index Page
    </div>
  )
}

export default Home
