import type {NextPage} from 'next'
import Head from 'next/head'
import LandingLayout from "../layout/landing.layout";

const Home: NextPage = () => {
    return (
        <LandingLayout>
            <Head>
                <title>NNM STARTER</title>
                <meta name="description" content="Generated by EXPRESSD3V WEB ENGINEERS"/>
            </Head>
        </LandingLayout>
    )
}

export default Home
