import React from 'react';
import {NextPage} from "next";
import Head from "next/head";
import LandingLayout from "../../layout/landing.layout";
import Container from '../../components/style/paper/container/index.style';
import {Card, Col, Row} from 'antd';
import Link from 'next/link';

interface PageProps {
    posts: any[];
}

const BlogsPage: NextPage<PageProps> = ({posts}) => {
    return (
        <LandingLayout>
            <Head>
                <title>BLOGS | NNM STARTER</title>
                <meta name="description" content="Generated by EXPRESSD3V WEB ENGINEERS"/>
            </Head>
            <Container>
                <Row>
                    {
                        posts.map((post, key) => (
                            <Col key={key} span={8}>
                                <Card>
                                    <h2>
                                        <Link href={`/blog/${post.slug}`}>
                                            <a>{post.title}</a>
                                        </Link>
                                    </h2>
                                </Card>
                            </Col>
                        ))
                    }
                </Row>
            </Container>
        </LandingLayout>
    );
};

export async function getStaticProps() {
    const posts = [
        {
            id: 'id',
            slug: 'slug-text',
            title: "POST TITLE"
        },
        {
            id: 'id1',
            slug: 'slug-text1',
            title: "POST TITLE1"
        }
    ]
    return {
        props: {
            posts,
        },
    }
}


export default BlogsPage;